### ISSUE TITLE
Skaffa Heroku konto

### ISSUE THREAD

**Issue by willeeklund** [jeespers/recipe_app#1]
- [x] Skapa konto på Heroku
- [x] Installera Heroku toolbelt
- [x] Logga in genom kommandoraden. Har för mig att det är "heroku login", kolla upp.

**Comment by willeeklund** [comment]
@jeespers Här går det undan i workflowet, snyggt! 👍

**Comment by jeespers** [comment]
@willeeklund Den första issue/ticket var ju tillräckligt lätt för att bli av med den direkt ;)
Frågan är dock om den behöver en review?

**Comment by willeeklund** [comment]
@jeespers Nej den tycker jag inte behöver någon review. Bra jobbat! Ser att du satt igång med nummer två också, strålande!
