### ISSUE TITLE
Skapa Heroku app som kör Go

### ISSUE THREAD

**Issue by willeeklund** [jeespers/recipe_app#2]
Följ Herokus instruktioner. 

Med Heroku så kan man välja vilket build pack som ska användas.
Ex för Go så finns https://github.com/heroku/heroku-buildpack-go.

- [x] Skapa Heroku applikation
- [x] Anslut det här repot så att du lokalt kan pusha till Heroku repot. Står i setup instruktioner hur man gör.

**Comment by willeeklund** [comment]
@jeespers För att kunna reviewa den här så skulle jag vilja veta vilken URL på Heroku man hittar den på.

**Comment by jeespers** [comment]
@willeeklund Finns nu i readme och [här!](https://stark-inlet-87958.herokuapp.com/)

**Comment by willeeklund** [comment]
Snyggt!
