### ISSUE TITLE
Använd en template engine

### ISSUE THREAD

**Issue by willeeklund** [jeespers/recipe_app#3]
- [x] Sätt upp en endpoint "/", som genererar en html-sida från en template.

**Comment by willeeklund** [comment]
Hur går det med den här? Det finns väl ett inbyggt template system i Go?

**Comment by jeespers** [comment]
Den är i stort sätt klar, ska commita den när jag kommer hem

**Comment by jeespers** [comment]
Prova att öppna sidan och lägg till en endpoint [typ](https://stark-inlet-87958.herokuapp.com/WhatEverYouWant)

**Comment by willeeklund** [comment]
Snyggt jobbat! Check.
